
export default interface Farmer {
  id?: number,
  page_number?:number,
  offset?:number,
  page_size?: number,
  filter_value?:any,
  name?: string,
  id_no?: string,
  status?: string,
  message?:string,
  principal_balance?:number,
  reference?:string,
  description?: string,
  interest?:number,
  destination?:string,
  wallet_balance?:number,
  origin?: string,
  gender?:string,
  pin?: number,
  passport_photo?:string,
  id_front_photo?:string, 
  id_back_photo?:string,
  age?: number,
  location?:string,
  msisdn?: string,
  latitude?: string,
  longitude?:string,
  
}