export default interface Loan {
	id?: number,
	farmer_id?: string,
	total_amount?: string,
	check_amount?: number,
	period_two?: number,
	reminder?: number,
	default_reminder?: number,
	insurance_fee?: string,
	monthly_instalment?: number,
	narrative?: string,
	period_three?: number,
	period?: number,
	total_interest?: number,
	livestock_id?: string,
	loan_reference?: string,
	narative?: string,
	interest_second?: number,
	interest_third?: number,
	insurance_instalment_third?: number,
	insurance_instalment_second?: number,
	monthly_instalment_second?: number,
	monthly_instalment_third?: number,
	rollover_fee?: number,
	debt_collection?: number,
	amount?: number,
	insurance_balance?: number,
	credit?: number,
	debit?: number,
	balance?: number,
	loan_id?: string,
	insurance_installment?: number,
	interest?: number,
	status?: string,
	reference?: string

}